/*
This file is part of TS3QueryApi For Go.
TS3QueryApi For Go is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
*/

package ts3const

const (
	SERVERINSTANCE_GUEST_SERVERQUERY_GROUP       = "SERVERINSTANCE_GUEST_SERVERQUERY_GROUP"
	SERVERINSTANCE_TEMPLATE_SERVERADMIN_GROUP    = "SERVERINSTANCE_TEMPLATE_SERVERADMIN_GROUP"
	SERVERINSTANCE_FILETRANSFER_PORT             = "SERVERINSTANCE_FILETRANSFER_PORT"
	SERVERINSTANCE_MAX_DOWNLOAD_TOTAL_BANDWITDH  = "SERVERINSTANCE_MAX_DOWNLOAD_TOTAL_BANDWITDH"
	SERVERINSTANCE_MAX_UPLOAD_TOTAL_BANDWITDH    = "SERVERINSTANCE_MAX_UPLOAD_TOTAL_BANDWITDH"
	SERVERINSTANCE_TEMPLATE_SERVERDEFAULT_GROUP  = "SERVERINSTANCE_TEMPLATE_SERVERDEFAULT_GROUP"
	SERVERINSTANCE_TEMPLATE_CHANNELDEFAULT_GROUP = "SERVERINSTANCE_TEMPLATE_CHANNELDEFAULT_GROUP"
	SERVERINSTANCE_TEMPLATE_CHANNELADMIN_GROUP   = "SERVERINSTANCE_TEMPLATE_CHANNELADMIN_GROUP"
	SERVERINSTANCE_SERVERQUERY_FLOOD_COMMANDS    = "SERVERINSTANCE_SERVERQUERY_FLOOD_COMMANDS"
	SERVERINSTANCE_SERVERQUERY_FLOOD_TIME        = "SERVERINSTANCE_SERVERQUERY_FLOOD_TIME"
	SERVERINSTANCE_SERVERQUERY_FLOOD_BAN_TIME    = "SERVERINSTANCE_SERVERQUERY_FLOOD_BAN_TIME"

	VIRTUALSERVER_NAME                                         = "VIRTUALSERVER_NAME"
	VIRTUALSERVER_WELCOMEMESSAGE                               = "VIRTUALSERVER_WELCOMEMESSAGE"
	VIRTUALSERVER_MAXCLIENTS                                   = "VIRTUALSERVER_MAXCLIENTS"
	VIRTUALSERVER_PASSWORD                                     = "VIRTUALSERVER_PASSWORD"
	VIRTUALSERVER_HOSTMESSAGE                                  = "VIRTUALSERVER_HOSTMESSAGE"
	VIRTUALSERVER_HOSTMESSAGE_MODE                             = "VIRTUALSERVER_HOSTMESSAGE_MODE"
	VIRTUALSERVER_DEFAULT_SERVER_GROUP                         = "VIRTUALSERVER_DEFAULT_SERVER_GROUP"
	VIRTUALSERVER_DEFAULT_CHANNEL_GROUP                        = "VIRTUALSERVER_DEFAULT_CHANNEL_GROUP"
	VIRTUALSERVER_DEFAULT_CHANNEL_ADMIN_GROUP                  = "VIRTUALSERVER_DEFAULT_CHANNEL_ADMIN_GROUP"
	VIRTUALSERVER_MAX_DOWNLOAD_TOTAL_BANDWIDTH                 = "VIRTUALSERVER_MAX_DOWNLOAD_TOTAL_BANDWIDTH"
	VIRTUALSERVER_MAX_UPLOAD_TOTAL_BANDWIDTH                   = "VIRTUALSERVER_MAX_UPLOAD_TOTAL_BANDWIDTH"
	VIRTUALSERVER_HOSTBANNER_URL                               = "VIRTUALSERVER_HOSTBANNER_URL"
	VIRTUALSERVER_HOSTBANNER_GFX_URL                           = "VIRTUALSERVER_HOSTBANNER_GFX_URL"
	VIRTUALSERVER_HOSTBANNER_GFX_INTERVAL                      = "VIRTUALSERVER_HOSTBANNER_GFX_INTERVAL"
	VIRTUALSERVER_COMPLAIN_AUTOBAN_COUNT                       = "VIRTUALSERVER_COMPLAIN_AUTOBAN_COUNT"
	VIRTUALSERVER_COMPLAIN_AUTOBAN_TIME                        = "VIRTUALSERVER_COMPLAIN_AUTOBAN_TIME"
	VIRTUALSERVER_COMPLAIN_REMOVE_TIME                         = "VIRTUALSERVER_COMPLAIN_REMOVE_TIME"
	VIRTUALSERVER_MIN_CLIENTS_IN_CHANNEL_BEFORE_FORCED_SILENCE = "VIRTUALSERVER_MIN_CLIENTS_IN_CHANNEL_BEFORE_FORCED_SILENCE"
	VIRTUALSERVER_PRIORITY_SPEAKER_DIMM_MODIFICATOR            = "VIRTUALSERVER_PRIORITY_SPEAKER_DIMM_MODIFICATOR"
	VIRTUALSERVER_ANTIFLOOD_POINTS_TICK_REDUCE                 = "VIRTUALSERVER_ANTIFLOOD_POINTS_TICK_REDUCE"
	VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_COMMAND_BLOCK        = "VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_COMMAND_BLOCK"
	VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_IP_BLOCK             = "VIRTUALSERVER_ANTIFLOOD_POINTS_NEEDED_IP_BLOCK"
	VIRTUALSERVER_HOSTBANNER_MODE                              = "VIRTUALSERVER_HOSTBANNER_MODE"
	VIRTUALSERVER_HOSTBUTTON_TOOLTIP                           = "VIRTUALSERVER_HOSTBUTTON_TOOLTIP"
	VIRTUALSERVER_HOSTBUTTON_GFX_URL                           = "VIRTUALSERVER_HOSTBUTTON_GFX_URL"
	VIRTUALSERVER_HOSTBUTTON_URL                               = "VIRTUALSERVER_HOSTBUTTON_URL"
	VIRTUALSERVER_DOWNLOAD_QUOTA                               = "VIRTUALSERVER_DOWNLOAD_QUOTA" // MByte
	VIRTUALSERVER_UPLOAD_QUOTA                                 = "VIRTUALSERVER_UPLOAD_QUOTA"   // MByte
	VIRTUALSERVER_MACHINE_ID                                   = "VIRTUALSERVER_MACHINE_ID"
	VIRTUALSERVER_PORT                                         = "VIRTUALSERVER_PORT"
	VIRTUALSERVER_AUTOSTART                                    = "VIRTUALSERVER_AUTOSTART"
	VIRTUALSERVER_STATUS                                       = "VIRTUALSERVER_STATUS"
	VIRTUALSERVER_LOG_CLIENT                                   = "VIRTUALSERVER_LOG_CLIENT"
	VIRTUALSERVER_LOG_QUERY                                    = "VIRTUALSERVER_LOG_QUERY"
	VIRTUALSERVER_LOG_CHANNEL                                  = "VIRTUALSERVER_LOG_CHANNEL"
	VIRTUALSERVER_LOG_PERMISSIONS                              = "VIRTUALSERVER_LOG_PERMISSIONS"
	VIRTUALSERVER_LOG_SERVER                                   = "VIRTUALSERVER_LOG_SERVER"
	VIRTUALSERVER_LOG_FILETRANSFER                             = "VIRTUALSERVER_LOG_FILETRANSFER"
	VIRTUALSERVER_MIN_CLIENT_VERSION                           = "VIRTUALSERVER_MIN_CLIENT_VERSION"
	VIRTUALSERVER_NEEDED_IDENTITY_SECURITY_LEVEL               = "VIRTUALSERVER_NEEDED_IDENTITY_SECURITY_LEVEL"
	VIRTUALSERVER_NAME_PHONETIC                                = "VIRTUALSERVER_NAME_PHONETIC"
	VIRTUALSERVER_ICON_ID                                      = "VIRTUALSERVER_ICON_ID"
	VIRTUALSERVER_RESERVED_SLOTS                               = "VIRTUALSERVER_RESERVED_SLOTS"
	VIRTUALSERVER_WEBLIST_ENABLED                              = "VIRTUALSERVER_WEBLIST_ENABLED"
	VIRTUALSERVER_CODEC_ENCRYPTION_MODE                        = "VIRTUALSERVER_CODEC_ENCRYPTION_MODE"
)
